### ISSUE TITLE
Bad contrast on FS3 website

### ISSUE THREAD

**Issue by Gilbert189** [realicraft/FightSim#2]
Black text on dark gray looks terrible. I propose to change the background to light gray or the text to white.

At the moment, the webpage looks like this.
![image](https://user-images.githubusercontent.com/57717273/132086437-3b41d3cc-2657-4b79-bad4-9f323561a1fe.png)

**Comment by realicraft** [comment]
Fixed in 237f1d8b1b4482d81118bf236edbee9f6a49595e. (Turn 31)
